platform :ios, '12.0'

ENV['FLUTTER_ROOT'] ||= `flutter --cache-dir`.strip
load File.join(ENV['FLUTTER_ROOT'], 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end
