# .github/workflows/ci_build.yml

on:
  push:
    branches: [ main ]

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file with Mapbox token
        run: echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/goblingo-release-key.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storeFile=goblingo-release-key.jks
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          EOF

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: goblingo-android-apk
          path: build/app/outputs/flutter-apk/*.apk

  build_ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up Ruby (for CocoaPods)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install

      - name: Create .env file with Mapbox token
        run: echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Clean build (optional but helps avoid iOS edge cases)
        run: flutter clean

      - name: Build iOS (no codesign)
        run: flutter build ipa --no-codesign

      - name: Upload iOS IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: goblingo-ios-ipa
          path: build/ios/ipa/*.ipa
