# .github/workflows/ci_build.yml

on:
  push:
    branches: [ main ]

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file with Mapbox token
        run: |
          echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: goblingo-android-apk
          path: build/app/outputs/flutter-apk/*.apk

  build_ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file with Mapbox token
        run: |
          echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: goblingo-ios-ipa
          path: build/ios/ipa/*.ipa