# .github/workflows/main.yml
name: CI (Analyze, Test, Build APK & IPA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install Flutter SDK (stable channel)
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3) Fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4) Static analysis
      - name: Run analyzer
        run: flutter analyze --no-fatal-warnings

      # 5) Unit tests
      - name: Run tests
        run: flutter test --coverage

      # 6) Build release APK (split per ABI)
      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      # 7) Upload APK as workflow artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: goblingo-android-apk
          path: build/app/outputs/flutter-apk/*.apk

  ios:
    name: iOS Build
    runs-on: macos-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install Flutter SDK (stable channel)
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3) Fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4) Static analysis
      - name: Run analyzer
        run: flutter analyze --no-fatal-warnings

      # 5) Unit tests
      - name: Run tests
        run: flutter test --coverage

      # 6) Build iOS release (no code signing)
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 7) Upload IPA as workflow artifact
      - name: Upload iOS IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: goblingo-ios-ipa
          path: build/ios/ipa/*.ipa
